# Generated by Django 4.0 on 2022-04-18 12:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_normaluser_nickname_normaluser_qq_number_and_more'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='digitalfile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='digitalfile',
            name='basic_information',
        ),
        migrations.RemoveField(
            model_name='digitalfile',
            name='health_condition',
        ),
        migrations.RemoveField(
            model_name='digitalfile',
            name='monthly_income',
        ),
        migrations.RemoveField(
            model_name='digitalfile',
            name='name_of_family_member',
        ),
        migrations.RemoveField(
            model_name='digitalfile',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='digitalfile',
            name='relationship',
        ),
        migrations.AlterField(
            model_name='digitalfile',
            name='height',
            field=models.FloatField(null=True, verbose_name='身高'),
        ),
        migrations.AlterField(
            model_name='digitalfile',
            name='investigator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigator', to='accounts.normaluser', verbose_name='调查人'),
        ),
        migrations.AlterField(
            model_name='digitalfile',
            name='weight',
            field=models.FloatField(null=True, verbose_name='体重'),
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('name_of_family_member', models.CharField(blank=True, max_length=20, verbose_name='姓名')),
                ('relationship', models.CharField(blank=True, max_length=20, verbose_name='与孩子的关系')),
                ('age', models.IntegerField(null=True, verbose_name='年龄')),
                ('occupation', models.CharField(blank=True, max_length=100, verbose_name='职业')),
                ('monthly_income', models.CharField(blank=True, max_length=100, verbose_name='月收入')),
                ('health_condition', models.CharField(blank=True, max_length=100, verbose_name='健康状况')),
                ('basic_information', models.CharField(blank=True, max_length=200, verbose_name='基本情况')),
                ('investigated_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigated_child', to='posts.digitalfile', verbose_name='被调查对象')),
            ],
            options={
                'verbose_name': '家庭情况（成员）表',
                'verbose_name_plural': '家庭情况（成员）表',
                'get_latest_by': 'id',
            },
        ),
    ]
