# Generated by Django 4.0 on 2022-04-22 09:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0003_blogsettings'),
        ('accounts', '0003_remove_normaluser_nickname_normaluser_qq_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='评论时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('comment_body', models.TextField(max_length=300, verbose_name='评论正文')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否显示')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.article', verbose_name='评论文章')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.normaluser', verbose_name='评论者')),
                ('parents_comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.comments', verbose_name='上级评论')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['-post_time'],
                'get_latest_by': 'id',
            },
        ),
    ]
