# Generated by Django 4.0 on 2022-04-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_normaluser_clean_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normaluser',
            name='nickname',
        ),
        migrations.AddField(
            model_name='normaluser',
            name='QQ_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='QQ号'),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='phone_number',
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='weixin_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='微信号'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='clean_password',
            field=models.CharField(blank=True, max_length=100, verbose_name='密码'),
        ),
    ]
